baseURL = 'https://example.org/'
languageCode = 'zh-tw'
title = 'å±è›‹ç¬¬äºŒè…¦'
theme = 'dream'
defaultContentLanguage = 'en'
canonifyurls = true

[services]
[services.googleAnalytics]
ID = "8186948356"

[params]
lightTheme = "emerald"
darkTheme = "forest"
avatar = 'images/stanmanBrain.png'
author = "å±è›‹"
description = "æ˜¯å¦æœ‰é¡å¼çš„ç¶“é©—ï¼Œæ¯æ¬¡çœ‹å®Œæ›¸å…§çš„æŸçš„ç« ç¯€ï¼Œæ„Ÿè¦ºå’Œéå»çœ‹éçš„å“ªæœ¬æ›¸å¾ˆåƒï¼Œå¯æ˜¯å°±æ˜¯æƒ³ä¸èµ·ä¾†ï¼Œç„¶å¾Œå†éå¹¾å¤©ï¼Œæˆ‘å­¸éçš„çŸ¥è­˜é»å°±å¿˜äº†ã€‚æ—¢ç„¶æˆ‘çš„è…¦è¢‹é€™éº¼æœƒå¿˜è¨˜ï¼Œä½•ä¸æˆ‘å°±æŠŠå­¸éçš„çŸ¥è­˜ä¸Ÿåˆ°æˆ‘çš„ç¬¬äºŒè…¦ï¼Œç„¶å¾Œæˆ‘å°±å¯ä»¥å®‰å¿ƒçš„å¿˜æ‰ï¼Œé€™å°±æ˜¯é€™å€‹ç¶²ç«™èª•ç”Ÿçš„ç”±ä¾†äº†"
headerTitle = "å±è›‹ç¬¬äºŒè…¦"
motto = "è…¦è¢‹æ˜¯ç”¨ä¾†æ€è€ƒçš„ è€Œä¸æ˜¯ç”¨ä¾†è¨˜æ±è¥¿çš„"
footerBottomText = "ğŸŒ± powered by Stan Man Brain."

showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true

reorderShares = ["facebook", "instagram"]

rss = true

reorderNavItems = ["search", "about", "categories", "tags" , "rss"]


waline = true
walineServer = "https://waline-iota-dusky.vercel.app/"

[params.advanced]
customCSS = ["css/custom.css"]
